#ifndef ENUMS_H
#define ENUMS_H

enum EventType
{
	EVENT_TYPE_FIRST 			= 0,
	EVENT_TYPE_INPUT_FIRST 		= EVENT_TYPE_FIRST,
	EVENT_TYPE_INPUT_KEY_DOWN	= EVENT_TYPE_INPUT_FIRST,
	EVENT_TYPE_INPUT_KEY_UP,
	EVENT_TYPE_INPUT_LAST 		= EVENT_TYPE_INPUT_KEY_UP,
	EVENT_TYPE_LAST
};

static bool isInputType(EventType eventType) { return (eventType >= EVENT_TYPE_INPUT_FIRST && eventType <= EVENT_TYPE_INPUT_LAST); }

enum Keys
{
	KEY_UP,
	KEY_DOWN,
	KEY_RIGHT,
	KEY_LEFT,
	KEY_ESC,
	KEY_CHAR_C,
	KEY_CHAR_CAP_C
};

enum Commands
{
	COMMAND_INCREASE_UPPER_CIRCLE_VELOCITY,
	COMMAND_DECREASE_UPPER_CIRCLE_VELOCITY,
	COMMAND_INCREASE_LOWER_CIRCLE_VELOCITY,
	COMMAND_DECREASE_LOWER_CIRCLE_VELOCITY,
};

#endif